@startuml flowKelolaBarang
start
:Pilih menu Kelola Barang;
repeat
:Lihat daftar data barang;
if (Lanjut?) then (Ya)
  if (Pilih Opsi?) then (Tambah)
    :Input data barang baru;
  else (Hapus)
    :Pilih data barang;
    :Hapus data;
  endif
else (Tidak)
  stop
endif
@enduml