@startuml activityPeminjamanBarang
|Admin|
start
:Pilih menu Peminjaman Barang;

|UI|
:Request data ke BLL;

|BLL|
:Ambil data barang ke DAL;

|DAL|
:Kirim data ke BLL;

|BLL|
:Kirim data ke UI;

|UI|
:Tampilkan daftar barang untuk dipinjam;

|Admin|
if (Jadi pinjam?) then (Ya)
  repeat
    |Admin|
    :Input form peminjaman;
    :Klik Konfirmasi;

    |UI|
    :Kirim data ke BLL;

    |BLL|
    :Validasi input (tidak kosong);

    |DAL|
    :Simpan data peminjaman ke Database;

    |UI|
    :Tampilkan Konfirmasi Berhasil;

    |Admin|
  repeat while (Pinjam lagi?) is (Ya)
  ->Tidak;
  :Kembali ke dashboard;
else (Tidak)
endif

stop
@enduml