@startuml RAT
entity "user" {
  *idUser : INT <<PK>>
  --
  username : VARCHAR(50) not null
  password : VARCHAR(255) not null
}
entity "Barang" {
  *idBarang : INT <<PK>>
  --
  namaBarang : VARCHAR(100)
  spesifikasi : VARCHAR(50)
  stok : INT not null
  tipeBarang : VARCHAR(50) not null
}

entity "detailBarang" {
  *idDetail : INT <<PK>>
  --
  idBarang : INT <<FK>>
  idRuangan : INT <<FK>>
}

entity "Permintaan" {
  *idPinjam : INT <<PK>>
  --
  idDetail : INT <<FK>>
  namaPeminta : VARCHAR(100)
  jumlah : INT
  tglPinjam : DATE
}

entity "Keryawan" {
  *idKaryawan : INT <<PK>>
  --
  namaKaryawan : VARCHAR(100) not null
}

entity "Maintenance" {
  *idCek : INT <<PK>>
  --
  idDetail : INT <<FK>>
  idKaryawan : INT <<FK>>
  tglCek : DATE
  kondisi : BIT not null
  tindakLanjut : VARCHAR(100)
}

entity "gedung" {
  *idGedung : INT <<PK>>
  --
  namaGedung : VARCHAR(100) not null
}

entity "ruangan" {
  *idRuangan : INT <<PK>>
  --
  namaRuangan : VARCHAR(100) not null
  idGedung : INT <<FK>>
}

' Setiap detail barang wajib punya 1 Barang
Barang ||--o{ detailBarang : "memiliki"

' Setiap ruangan wajib ada di 1 gedung (Mandatory One)
gedung ||--o{ ruangan : "memiliki"

' satu detail barang bisa di banyak ruangan dan satu ruangan bisa menyimpan banyak/nol detail barang 
ruangan }o--o{ detailBarang : "menyimpan"

' 1 unit bisa berkali-kali dipinjam/dirawat)
detailBarang ||--o{ Permintaan : "diminta"
detailBarang ||--o{ Maintenance : "dirawat"

' minimal 1 karyawan untuk bisa melakukan maintenance
Keryawan ||--o{ Maintenance : "melakukan"

@enduml