@startuml usecaseReport
left to right direction
actor Admin

rectangle "Sistem Report" {
  usecase "Lihat Status Barang" as UC1
  usecase "Cetak Report (Excel)" as UC2
  usecase "Login" as UC3
}

Admin -- UC3
UC3 -- UC1
UC3 -- UC2
@enduml