@startuml usecasePengecekanRutin
left to right direction
actor Admin

rectangle "Sistem Pengecekan Rutin" {
  usecase "CRUD Data Pengecekan" as UC1
  usecase "Lihat Riwayat Pengecekan" as UC2
  usecase "Login" as UC3
}

Admin -- UC3
UC3 -- UC1
UC3 -- UC2
@enduml