@startuml usecaseMaintenance
left to right direction
actor Admin

rectangle "Sistem Maintenance" {
  usecase "Lihat Data Maintenance" as UC1
  usecase "Kelola Data Maintenance (CRUD)" as UC2
  usecase "Login" as UC3
}

Admin -- UC3
UC3 -- UC1
UC3 -- UC2
@enduml