@startuml usecaseKelolaBarang
left to right direction
actor Admin

rectangle "Sistem Kelola Barang" {
  usecase "Lihat Data Barang" as UC1
  usecase "Tambah Data Barang" as UC2
  usecase "Hapus Data Barang" as UC3
  usecase "Login" as UC4
}

Admin -- UC4
UC4 -- UC1
UC4 -- UC2
UC4 -- UC3
@enduml