@startuml activityPengecekanRutin
|Admin|
start
:Membuka aplikasi;

|Sistem|
:Tampilkan halaman login;

|Admin|
:Login dengan username dan password;

|Sistem|
:Validasi login & tampilkan halaman utama;

|Admin|
:Pilih menu Pengecekan Rutin;

|Sistem|
:Tampilkan halaman Pengecekan Rutin;

|Admin|
if (Ingin isi form pengecekan?) then (Ya)
  repeat
    |Admin|
    :Isi form pengecekan;
    :Klik Simpan;
    |Sistem|
    :Proses simpan & tampilkan konfirmasi;
    |Admin|
  repeat while (Lanjut isi form?) is (Ya)
  ->Tidak;
  :Kembali ke halaman Pengecekan Rutin;
else (Tidak)
  :Kembali ke halaman pengecekan rutin;
endif

stop
@enduml