@startuml activityMaintenance

|Admin|
start
:Membuka Aplikasi;

|Sistem|
:Tampilkan Halaman Login;

|Admin|
:Input Username & Password;

|Sistem|
:Validasi Akun;
if (Login Berhasil?) then (Ya)
  :Tampilkan Halaman Utama;
else (Tidak)
  :Tampilkan Pesan Error;
  :Kembali ke Halaman Login;
  detach
endif

|Admin|
:Pilih Menu Maintenance;

|Sistem|
:Tampilkan Daftar & Form Maintenance;

|Admin|
if (Input Data Maintenance Baru?) then (Ya)
  repeat
    |Admin|
    :Isi Detail Perbaikan/Maintenance;
    :Klik Tombol Simpan;
    
    |Sistem|
    :Validasi Input Data;
    :Simpan Log Maintenance ke satprasDB;
    :Tampilkan Notifikasi Berhasil;
    :Refresh Daftar Maintenance;
    
    |Admin|
  repeat while (Tambah Data Lagi?) is (Ya)
  ->Tidak;
else (Hanya Lihat Data)
endif

|Admin|
:Kembali ke Halaman Utama;
stop

@enduml