@startuml activityReport
|Admin|
start
:Membuka aplikasi;
|Sistem|
:Tampilkan halaman login;
|Admin|
:Login dengan username dan password;
|Sistem|
:Validasi login & tampilkan halaman utama;
|Admin|
:Klik tombol Report;
|Sistem|
:Tampilkan halaman Report;

|Admin|
if (Ingin cetak ke Excel?) then (Ya)
  |Sistem|
  :Tampilkan file Excel;
  |Admin|
  :Download dan Simpan file ke komputer;
else (Tidak/Hanya Lihat)
  |Admin|
  :Kembali ke halaman report;
endif

stop
@enduml