@startuml activityPengecekanRutin

|Admin|
start
:Membuka Aplikasi;

|Sistem|
:Tampilkan Halaman Login;

|Admin|
:Input Email & Password;

|Sistem|
:Validasi Akun;
if (Login Berhasil?) then (Ya)
  :Tampilkan Halaman Utama;
else (Tidak)
  :Tampilkan Pesan Error;
  :Kembali ke Halaman Login;
  detach
endif

|Admin|
:Pilih Menu Pengecekan Rutin;

|Sistem|
:Tampilkan Daftar Pengecekan & Form;

|Admin|
if (Tambah Pengecekan Baru?) then (Ya)
  repeat
    |Admin|
    :Isi Detail Kondisi Barang;
    :Klik Tombol Simpan;
    
    |Sistem|
    :Validasi Input;
    :Simpan Data ke satprasDB;
    :Tampilkan Notifikasi Sukses;
    
    |Admin|
  repeat while (Input Barang Lain?) is (Ya)
  ->Tidak;
else (Hanya Lihat Data)
endif

|Admin|
:Kembali ke Halaman Utama;
stop

@enduml