@startuml activityKelolaBarang

|Admin|
start
:Membuka aplikasi;

repeat

  |Sistem|
  :Tampilkan halaman login;

  |Admin|
  :Masukkan username dan password;

  |Sistem|
  :Validasi Akun;



repeat while (Login gagal?) is (Ya)

|Admin|
:Pilih menu Kelola Barang;

|Sistem|
:Tampilkan halaman Kelola Barang;

|Admin|
if (Ingin Tambah Barang?) then (Ya)

  |Sistem|
  repeat
    :Tampilkan form tambah barang;

    |Admin|
    :Input data barang;
    :Klik Simpan;

    |Sistem|
    if (Input Valid?) then (Ya)
      :Simpan data permintaan ke satprasDB;
      :Tampilkan notifikasi sukses;
    else (Tidak)
      :Fail-safe mode;
      :Tampilkan pesan error;
    endif

    |Admin|

  repeat while (Tambah barang lagi?) is (Ya)

  |Sistem|
  :Kembali ke halaman Kelola Barang;

else (Tidak)

endif

stop
@enduml