@startuml activityPeminjamanBarang
|Admin|
start
:Membuka aplikasi;
|Sistem|
:Tampilkan halaman login;
|Admin|
:Login dengan username dan password;
|Sistem|
:Validasi Akun;
if (Login Berhasil?) then (Ya)
  :Tampilkan Halaman Utama;
else (Tidak)
  :Tampilkan Pesan Error;
  :Kembali ke Halaman Login;
  detach
endif
|Admin|
:Pilih menu Permintaan Barang;
|Sistem|
:Tampilkan daftar barang untuk dipinjam;

|Admin|
if (Jadi pinjam?) then (Ya)
  repeat
    |Admin|
    :Input form Permintaan Barang;
    :Klik Konfirmasi;
    |Sistem|
    :validasi input;
    if (Input Valid?) then (Ya)
      :Simpan data permintaan ke satprasDB;
      :Tampilkan notifikasi sukses;
    else (Tidak)
      :Tampilkan pesan error;
      :fail safe;
    endif


    |Admin|
  repeat while (Pinjam lagi?) is (Ya)
  ->Tidak;
  :Kembali ke dashboard;
else (Tidak)
endif

stop
@enduml