@startuml activityPeminjamanBarang
|Admin|
start
:Membuka aplikasi;
|Sistem|
:Tampilkan halaman login;
|Admin|
:Login dengan username dan password;
|Sistem|
:Validasi login & tampilkan halaman utama;
|Admin|
:Pilih menu Permintaan Barang;
|Sistem|
:Tampilkan daftar barang untuk dipinjam;

|Admin|
if (Jadi pinjam?) then (Ya)
  repeat
    |Admin|
    :Input form Permintaan Barang;
    :Klik Konfirmasi;
    |Sistem|
    :Simpan data & Tampilkan Konfirmasi Berhasil;

    |Admin|
  repeat while (Pinjam lagi?) is (Ya)
  ->Tidak;
  :Kembali ke dashboard;
else (Tidak)
endif

stop
@enduml