@startuml activityMaintenance
|Admin| 
start
:Membuka aplikasi;

|Sistem|
:Tampilkan halaman login;

|Admin|
:Login dengan username dan password;

|Sistem|
:Validasi login;
:Menampilkan halaman utama;

|Admin|
:Memilih menu Maintenance;

|Sistem|
:Menampilkan halaman Maintenance;

|Admin|
if (input maintenance) then (Ya)
  |Sistem|
  repeat
    :Tampilkan form tambah barang;
    |Admin|
    :Input data;
    :Klik Simpan;
    |Sistem|
    :Proses simpan & tampilkan konfirmasi;
    :kembali ke halaman Maintenance;
    |Admin|
  repeat while (Tambah barang lagi?) is (Ya)
  ->Tidak;
  :Kembali ke halaman Kelola Barang;
else (Tidak)
endif
stop
@enduml